# Site settings
title: 姜茶.Blog
SEOTitle: 姜茶的博客 | Mcoder's Blog
header-img: img/header.jpg
email: mcoder2014@sina.com
description: "一个涉猎广泛的程序员"
keyword: "姜茶 超群 博客 blog app android DL Deep Learning Ml Machine Learning"
url: "https://mcoder2014.github.io/"          # your host, for absolute URL
baseurl: ""                                 # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/mcoder2014" # you code repository

# Sidebar settings
sidebar: true                               # whether or not using Sidebar.
sidebar-about-description: "在热爱编程技术的同时还热爱摄影"
sidebar-avatar: /img/about.png    # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-weixin: /img/qrcode_for_gh_a5dae253d93f_344.jpg    # 微信公众号二维码

# SNS settings
RSS: false
#weibo_username:     mcoder2014
zhihu_username:     mcoder2014
github_username:    mcoder2014
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying
csdn_username: jcq521045349
lofter_url: "https://jiangcha219.lofter.com/"

# Build settings
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# if you want to customize anchor.
anchorjs: true                          

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# compare with jekylll 4.0
plugins_dir: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM    # use Github Flavored Markdown !important

# 站点访问量统计
# Google Analytics
ga_track_id: 'UA-110491207-1'            # Format: UA-xxxxxx-xx
ga_domain: auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# 友情链接
friends: [
    {
        title: "CG-HHU",
        href: "https://cghhu.cn/"
    },
    {
        title: "LLJ-STAR",
        href: "https://lljstar.com/"
    },
    {
        title: "Userful Tools",
        href: "http://notes.cghhu.cn/"
    }]

theme: jekyll-theme-minimal
